### ISSUE TITLE
Command to add gold missing

### ISSUE THREAD

**Issue by hkbbdx** [mserajnik/vmangos-deploy#3]
Hello!
I feel that you provide such a good project, and I have high respect for you. Thank you very much!
I want to add gold coins to my character, but I have tried many commands but they all say they are invalid.
GM commands
.modify money
.money
.modify gold
----------------------------------
I have used the server compiled by myself before. I can add gold coins by running .modify money 1000000. What is the problem?

**Comment by hkbbdx** [comment]
I added an administrator account with level 3
.gm on After turning on GM mode,
Unable to increase character's gold coins

**Comment by mserajnik** [comment]
Hi, sorry, I can't answer support questions relating to the upstream project here as I'm not affiliated; if some command is not working as before it was likely changed in VMaNGOS and has nothing to do with this Docker setup (as it doesn't do anything that would affect this).

If you can't figure it out yourself, please reach out in the [VMaNGOS repository](https://github.com/vmangos/core) instead. Thank you!
