### ISSUE TITLE
Error during initial deployment

### ISSUE THREAD

**Issue by RobertoAlamarGames** [mserajnik/vmangos-deploy#7]
[vmangos-deploy]: Configuration file /opt/vmangos/config/mangosd.conf is missing, exiting

On a new build, on the "vmangos-deploy-database-1" container, I am seeing the above error message, and the container perpetually restarts. As expected, the other two containers show this error until their timers run out:

mangosd-1  | [INFO  wait] Host [database:3306] not yet available...
realmd-1  | [INFO  wait] Host [database:3306] not yet available...

Nothing in the base docker-compose file was changed, the *.conf files, nor any of the commands/procedures in the readme, with exception to the client data extraction, which completed successfully, but modified the command to this:

docker run -v D:\wow\vmangos-deploy\storage\mangosd\client-data:/opt/vmangos/storage/client-data -v D:\wow\vmangos-deploy\storage\mangosd\extracted-data:/opt/vmangos/storage/extracted-data --rm --user 1000:1000 ghcr.io/mserajnik/vmangos-server:5875 extract-client-data

This is on Windows 11 docker-compose.

**Comment by mserajnik** [comment]
```
[vmangos-deploy]: Configuration file /opt/vmangos/config/mangosd.conf is missing, exiting
```

That error indicates that the mangosd container can’t find the configuration file, which usually should only happen if you forget to copy the configuration file as instructed by the README (unless you changed the bind mount for the configuration file); this was a very recent addition because other users ran into that issue (because they didn’t read the README carefully enough) and this message was meant as an additional hint/safeguard.

But you are seeing this with the database container? That sounds like it’s using a wrong image, because the database image doesn’t even include the script which contains this check.

You are saying you didn’t change the default configuration, but please still post the full contents of your `compose.yml`, because otherwise this will be impossible to debug.

**Comment by RobertoAlamarGames** [comment]
My apologies, I deleted all images and re-started the process from scratch with a new git clone, and I can't re-create the issue. The only things I changed from the first deployment to the second are:

1.

docker run -v D:\wow\vmangos-deploy\storage\mangosd\client-data:/opt/vmangos/storage/client-data -v D:\wow\vmangos-deploy\storage\mangosd\extracted-data:/opt/vmangos/storage/extracted-data --rm --user 1000:1000 ghcr.io/mserajnik/vmangos-server:5875 extract-client-data

became this:

docker run -v D:/wow/vmangos-deploy/storage/mangosd/client-data:/opt/vmangos/storage/client-data -v D:/wow/vmangos-deploy/storage/mangosd/extracted-data:/opt/vmangos/storage/extracted-data --rm --user 1000:1000 ghcr.io/mserajnik/vmangos-server:5875 extract-client-data
[compose.yaml.txt](https://github.com/user-attachments/files/18242082/compose.yaml.txt)

2.

Instead of turning off my machine after extracting the client data and continuing the process in a later session, I left it on all night to finish extracting, and did not restart.

3.

I tried the initial docker compose up -d from an admin CMD prompt instead of the built-in Powershell terminal in VSCode.


I still attached the compose file, and below are the exact commands I used in order, along with their output (I left out the logs since I didn't get the same error this time, and it started just fine):

git clone https://github.com/mserajnik/vmangos-deploy.git
cd vmangos-deploy
cp ./config/mangosd.conf.example ./config/mangosd.conf
cp ./config/realmd.conf.example ./config/realmd.conf
cp ./compose.yaml.example ./compose.yaml

docker run -v D:/wow/vmangos-deploy/storage/mangosd/client-data:/opt/vmangos/storage/client-data -v D:/wow/vmangos-deploy/storage/mangosd/extracted-data:/opt/vmangos/storage/extracted-data --rm --user 1000:1000 ghcr.io/mserajnik/vmangos-server:5875 extract-client-data

docker compose up -d

PS D:\wow\vmangos-deploy> docker compose logs -f mangosd
mangosd-1  | [INFO  wait] --------------------------------------------------------
mangosd-1  | [INFO  wait]  docker-compose-wait 2.12.1
mangosd-1  | [INFO  wait] ---------------------------
mangosd-1  | [DEBUG wait] Starting with configuration:
mangosd-1  | [DEBUG wait]  - Hosts to be waiting for: [database:3306]
mangosd-1  | [DEBUG wait]  - Paths to be waiting for: []
mangosd-1  | [DEBUG wait]  - Timeout before failure: 600 seconds
mangosd-1  | [DEBUG wait]  - TCP connection timeout before retry: 5 seconds
mangosd-1  | [DEBUG wait]  - Sleeping time before checking for hosts/paths availability: 0 seconds
mangosd-1  | [DEBUG wait]  - Sleeping time once all hosts/paths are available: 0 seconds
mangosd-1  | [DEBUG wait]  - Sleeping time between retries: 1 seconds
 ✔ Network vmangos-deploy_default       Created                                                                                 0.0s 
 ✔ Container vmangos-deploy-database-1  Started                                                                                 0.9s 
 ✔ Container vmangos-deploy-realmd-1    Started                                                                                 1.1s 
 ✔ Container vmangos-deploy-mangosd-1   Started                                                                                 1.0s 

PS D:\wow\vmangos-deploy> docker compose logs -f mangosd
mangosd-1  | [INFO  wait] --------------------------------------------------------
mangosd-1  | [INFO  wait]  docker-compose-wait 2.12.1
mangosd-1  | [INFO  wait] ---------------------------
mangosd-1  | [DEBUG wait] Starting with configuration:
mangosd-1  | [DEBUG wait]  - Hosts to be waiting for: [database:3306]
mangosd-1  | [DEBUG wait]  - Paths to be waiting for: []
mangosd-1  | [DEBUG wait]  - Timeout before failure: 600 seconds
mangosd-1  | [DEBUG wait]  - TCP connection timeout before retry: 5 seconds
mangosd-1  | [DEBUG wait]  - Sleeping time before checking for hosts/paths availability: 0 seconds
 ✔ Network vmangos-deploy_default       Created                                                                                 0.0s 
 ✔ Container vmangos-deploy-database-1  Started                                                                                 0.9s 
 ✔ Container vmangos-deploy-realmd-1    Started                                                                                 1.1s 
 ✔ Container vmangos-deploy-mangosd-1   Started                                                                                 1.0s 
PS D:\wow\vmangos-deploy> docker compose logs -f mangosd
mangosd-1  | [INFO  wait] --------------------------------------------------------
 ✔ Network vmangos-deploy_default       Created                                                                                 0.0s 
 ✔ Container vmangos-deploy-database-1  Started                                                                                 0.9s 
 ✔ Container vmangos-deploy-realmd-1    Started                                                                                 1.1s 
 ✔ Container vmangos-deploy-mangosd-1   Started                                                                                 1.0s 
PS D:\wow\vmangos-deploy> docker compose logs -f mangosd
 ✔ Network vmangos-deploy_default       Created                                                                                 0.0s 
 ✔ Container vmangos-deploy-database-1  Started                                                                                 0.9s 
 ✔ Container vmangos-deploy-realmd-1    Started                                                                                 1.1s 
 ✔ Network vmangos-deploy_default       Created                                                                                 0.0s 
 ✔ Container vmangos-deploy-database-1  Started                                                                                 0.9s 
 ✔ Network vmangos-deploy_default       Created                                                                                 0.0s 
 ✔ Container vmangos-deploy-database-1  Started                                                                                 0.9s 
 ✔ Network vmangos-deploy_default       Created                                                                                 0.0s 
 ✔ Container vmangos-deploy-database-1  Started                                                                                 0.9s 
 ✔ Network vmangos-deploy_default       Created                                                                                 0.0s 
 ✔ Network vmangos-deploy_default       Created                                                                                 0.0s 
 ✔ Container vmangos-deploy-database-1  Started                                                                                 0.9s 
 ✔ Container vmangos-deploy-realmd-1    Started                                                                                 1.1s 
 ✔ Container vmangos-deploy-mangosd-1   Started                                                                                 1.0s

**Comment by mserajnik** [comment]
Thank you for the detailed reply.

As I mentioned before, I can’t think of a way how the database service (when using the `vmangos-database` image as it’s supposed to) could produce that error, as only the mangosd service (with the `vmangos-server` image) contains that specific check in its entrypoint script.

The things you mentioned, like changing the shell environment from which you run `docker compose up -d` or leaving the machine running versus turning it off after the client data extraction couldn’t have anything to do with this.

If you (yourself) didn’t consciously (or accidentally) change the database service to use the `vmangos-server` image the first time, I can only imagine that it got somehow edited without you noticing before starting the container; are you perhaps using Copilot or some other LLM in VS Code that might have “corrected”/auto-completed the image name wrongly?

Regardless, I’m glad you managed to get it working.
